export const mockTrends = [
    {
      id: 'mock-1',
      title: 'AI-Powered Job Interview Simulators',
      subreddit: 'startups',
      score: 842,
      url: 'https://reddit.com/r/startups/123',
      categories: ['ai', 'career'],
      description: 'Simulated AI interviews are trending as job seekers and platforms embrace AI-based preparation tools.',
      rating: 4,
      createdAt: new Date(),
    },
    {
      id: 'mock-2',
      title: 'Minimalist Skincare Lines for Gen Z',
      subreddit: 'skincareaddiction',
      score: 421,
      url: 'https://reddit.com/r/skincareaddiction/456',
      categories: ['beauty', 'ecommerce'],
      description: 'Gen Z is shifting toward ultra-simple skincare routines with just 2–3 essential products.',
      rating: 5,
      createdAt: new Date(),
    },
    {
      id: 'mock-3',
      title: 'Financial Education for Teen Investors',
      subreddit: 'financialindependence',
      score: 611,
      url: 'https://reddit.com/r/financialindependence/789',
      categories: ['finance', 'education'],
      description: 'Apps and courses targeting teenage financial literacy are gaining traction with both parents and educators.',
      rating: 4,
      createdAt: new Date(),
    },
    {
      id: 'mock-4',
      title: 'Fragrance Subscriptions are Making a Comeback',
      subreddit: 'fragrance',
      score: 315,
      url: 'https://reddit.com/r/fragrance/987',
      categories: ['retail', 'lifestyle'],
      description: 'Consumers are rediscovering personalized monthly fragrance boxes as niche perfume popularity spikes.',
      rating: 3,
      createdAt: new Date(),
    },
    {
      id: 'mock-5',
      title: 'No-Code Automations for Remote Teams',
      subreddit: 'sideproject',
      score: 507,
      url: 'https://reddit.com/r/sideproject/159',
      categories: ['remote work', 'tools'],
      description: 'Startups are building drag-and-drop workflow builders for async teams who don’t want to write code.',
      rating: 4,
      createdAt: new Date(),
    },
    {
      id: 'mock-6',
      title: 'AI-Assisted Meditation Coaches',
      subreddit: 'meditation',
      score: 298,
      url: 'https://reddit.com/r/meditation/753',
      categories: ['health', 'ai'],
      description: 'Mindfulness apps are testing GPT-based meditation guides that adjust to your emotional state in real-time.',
      rating: 5,
      createdAt: new Date(),
    },
    {
      id: 'mock-7',
      title: 'Digital Pop-Up Shops on TikTok',
      subreddit: 'Entrepreneur',
      score: 433,
      url: 'https://reddit.com/r/Entrepreneur/753',
      categories: ['ecommerce', 'marketing'],
      description: 'Pop-up sales events run directly inside TikTok lives are helping creators test product-market fit overnight.',
      rating: 4,
      createdAt: new Date(),
    },
    {
      id: 'mock-8',
      title: 'Personal AI for Learning a New Language',
      subreddit: 'selfimprovement',
      score: 349,
      url: 'https://reddit.com/r/selfimprovement/753',
      categories: ['ai', 'language learning'],
      description: 'AI agents are now being used to simulate conversation partners for language learners in specific dialects.',
      rating: 4,
      createdAt: new Date(),
    },
    {
      id: 'mock-9',
      title: 'Crowdfunded Skincare R&D Communities',
      subreddit: 'femalefashionadvice',
      score: 311,
      url: 'https://reddit.com/r/femalefashionadvice/753',
      categories: ['beauty', 'consumer brands'],
      description: 'Online skincare communities are crowdfunding product development and voting on active ingredient formulas.',
      rating: 3,
      createdAt: new Date(),
    },
    {
      id: 'mock-10',
      title: 'Voice-Powered Productivity Tools',
      subreddit: 'SaaS',
      score: 712,
      url: 'https://reddit.com/r/SaaS/753',
      categories: ['saas', 'ai'],
      description: 'Speech-to-task tools are turning voice commands into Trello cards, Jira tickets, and Slack messages in real time.',
      rating: 5,
      createdAt: new Date(),
    },
  ];
  